inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false